services:
  postgres:
    image: postgres:latest
    container_name: headless-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - headless-network

volumes:
  postgres_data:
    driver: local

networks:
  headless-network:
    driver: bridge
